-- phpMyAdmin SQL Dump
-- version 3.4.5
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Dec 19, 2011 at 08:30 AM
-- Server version: 5.5.16
-- PHP Version: 5.3.8

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `resume_extraction`
--

-- --------------------------------------------------------

--
-- Table structure for table `experience`
--

CREATE TABLE IF NOT EXISTS `experience` (
  `rid` int(11) NOT NULL,
  `experience` varchar(1000) NOT NULL,
  KEY `rid` (`rid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `experience`
--

INSERT INTO `experience` (`rid`, `experience`) VALUES
(1, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(2, 'N;'),
(3, 'N;'),
(4, 'a:12:{i:0;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:1;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:2;a:1:{s:9:"job_title";s:0:"";}i:3;a:1:{s:15:"job_description";N;}i:4;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:5;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:6;a:1:{s:9:"job_title";s:0:"";}i:7;a:1:{s:15:"job_description";N;}i:8;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:9;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:10;a:1:{s:9:"job_title";s:0:"";}i:11;a:1:{s:15:"job_description";N;}}'),
(5, 'a:12:{i:0;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:1;a:1:{s:5:"years";s:9:" 4\n			\n		";}i:2;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:5;a:1:{s:5:"years";s:9:" 5\n			\n		";}i:6;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n			'),
(6, 'a:12:{i:0;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:1;a:1:{s:5:"years";s:9:" 4\n			\n		";}i:2;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:5;a:1:{s:5:"years";s:9:" 5\n			\n		";}i:6;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n			'),
(7, 'a:12:{i:0;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:1;a:1:{s:5:"years";s:9:" 4\n			\n		";}i:2;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:5;a:1:{s:5:"years";s:9:" 5\n			\n		";}i:6;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n			'),
(8, 'a:12:{i:0;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:1;a:1:{s:5:"years";s:9:" 4\n			\n		";}i:2;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:5;a:1:{s:5:"years";s:9:" 5\n			\n		";}i:6;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n			'),
(9, 'a:12:{i:0;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:1;a:1:{s:5:"years";s:9:" 4\n			\n		";}i:2;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:5;a:1:{s:5:"years";s:9:" 5\n			\n		";}i:6;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n			'),
(10, 'a:12:{i:0;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:1;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:2;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:5;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:6;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n	'),
(11, 'a:12:{i:0;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:1;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:2;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:5;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:6;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n	'),
(12, 'a:12:{i:0;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:1;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:2;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:5;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:6;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n	'),
(1, 'a:12:{i:0;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:1;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:2;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:5;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:6;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n	'),
(2, 'a:12:{i:0;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:1;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:2;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n			\n				Company Name";}i:5;a:1:{s:5:"years";s:27:" Dates of Employment\n			\n		";}i:6;a:1:{s:9:"job_title";s:148:"\n			\n				\n				\n					\n					\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n				\n			\n				Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:124:"\n			\n				\n				\n					\n					\n					\n					\n					\n	'),
(3, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:19:"Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:19:"Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:19:"Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(4, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:19:"Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:19:"Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:19:"Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(5, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:19:"Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:19:"Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:19:"Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(6, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(7, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:19:"Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:19:"Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:19:"Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(8, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:19:"Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:19:"Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:19:"Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(9, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:1:"4";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:1:"5";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:1:"6";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(10, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(1, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:1:"4";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:1:"5";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:1:"6";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(2, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:1:"4";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:1:"5";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:1:"6";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(3, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:19:"Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:19:"Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:19:"Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(4, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:19:"Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:19:"Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:19:"Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(5, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:1:"4";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:1:"5";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:1:"6";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(6, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(7, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(8, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(9, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(10, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(11, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:1:"4";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:1:"5";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:1:"6";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(12, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:1:"4";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:1:"5";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:1:"6";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(13, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:1:"4";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:1:"5";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:1:"6";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(14, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:1:"4";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:1:"5";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:1:"6";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(15, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:1:"4";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:1:"5";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:1:"6";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(16, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:1:"4";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:1:"5";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:1:"6";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(17, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(18, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:19:"Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:19:"Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:19:"Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(19, 'a:0:{}'),
(20, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(21, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(22, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(23, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(24, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(25, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(26, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(27, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(28, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(29, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(30, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(1, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(2, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(3, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(4, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(5, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(6, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(7, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(8, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(9, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(10, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(1, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(2, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(3, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(4, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:19:"Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:19:"Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:19:"Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(1, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(2, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:19:"Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:19:"Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:19:"Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(3, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:1:"4";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:11:"description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:1:"5";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:11:"description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:1:"6";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:11:"description";}}'),
(5, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(6, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(1, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(2, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:20:" Dates of Employment";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:20:" Dates of Employment";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:20:" Dates of Employment";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(3, 'a:0:{}'),
(4, 'a:0:{}'),
(5, 'a:0:{}'),
(6, 'a:0:{}'),
(7, 'a:0:{}'),
(8, 'a:0:{}'),
(9, 'a:0:{}'),
(10, 'a:0:{}'),
(11, 'a:4:{i:0;a:1:{s:12:"company_name";s:16:"Â«Company_nameÂ»";}i:1;a:1:{s:5:"years";s:17:" Â«yearsÂ»  years";}i:2;a:1:{s:9:"job_title";s:13:"Â«job_titleÂ»";}i:3;a:1:{s:15:"job_description";s:20:" Â«job_descriptionÂ»";}}'),
(12, 'a:12:{i:0;a:1:{s:12:"company_name";s:12:"Company Name";}i:1;a:1:{s:5:"years";s:2:" 5";}i:2;a:1:{s:9:"job_title";s:9:"Job Title";}i:3;a:1:{s:15:"job_description";s:12:" description";}i:4;a:1:{s:12:"company_name";s:12:"Company Name";}i:5;a:1:{s:5:"years";s:2:" 6";}i:6;a:1:{s:9:"job_title";s:9:"Job Title";}i:7;a:1:{s:15:"job_description";s:12:" description";}i:8;a:1:{s:12:"company_name";s:12:"Company Name";}i:9;a:1:{s:5:"years";s:2:" 1";}i:10;a:1:{s:9:"job_title";s:9:"Job Title";}i:11;a:1:{s:15:"job_description";s:12:" description";}}'),
(13, 'a:0:{}'),
(14, 'a:4:{i:0;a:1:{s:12:"company_name";s:7:"Dlcmdlc";}i:1;a:1:{s:5:"years";s:8:"3  years";}i:2;a:1:{s:9:"job_title";s:6:"ss nks";}i:3;a:1:{s:15:"job_description";s:6:"e dked";}}');

-- --------------------------------------------------------

--
-- Table structure for table `resume`
--

CREATE TABLE IF NOT EXISTS `resume` (
  `uid` int(11) NOT NULL,
  `rid` int(11) NOT NULL AUTO_INCREMENT,
  `last_name` varchar(20) NOT NULL,
  `first_name` varchar(20) NOT NULL,
  `address` varchar(200) NOT NULL,
  `city` varchar(20) NOT NULL,
  `state` varchar(20) NOT NULL,
  `zip` varchar(20) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `email` varchar(20) NOT NULL,
  `degree` varchar(20) NOT NULL,
  `college` varchar(20) NOT NULL,
  `college_dates` varchar(20) NOT NULL,
  `awards` varchar(1000) NOT NULL,
  `skills` varchar(1000) NOT NULL,
  `experience` varchar(20) NOT NULL,
  `location` varchar(200) NOT NULL,
  PRIMARY KEY (`rid`),
  KEY `uid` (`uid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=15 ;

--
-- Dumping data for table `resume`
--

INSERT INTO `resume` (`uid`, `rid`, `last_name`, `first_name`, `address`, `city`, `state`, `zip`, `phone`, `email`, `degree`, `college`, `college_dates`, `awards`, `skills`, `experience`, `location`) VALUES
(1, 1, 'Â«Last_nameÂ»', 'Â«First_nameÂ»', 'Â«street_addressÂ»', ' Â«CityÂ»', ' Â«zipÂ»', ' Â«stateÂ»', 'Â«phone_noÂ»', 'Â«emailÂ»', 'School Name â€“ Scho', ' State', 'Dates of attendance', 'List employment, academic or other achievements|List employment, academic or other achievements|List employment, academic or other achievements|;', 'List computer, language or other personal skills here,List computer, language or other personal skills here,;', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/5616/license-agreement-document.docx'),
(1, 2, 'Â«Last_nameÂ»', 'Â«First_nameÂ»', 'Â«street_addressÂ»', ' Â«CityÂ»', ' Â«zipÂ»', ' Â«stateÂ»', 'Â«phone_noÂ»', 'Â«emailÂ»', 'School Name â€“ Scho', ' State', 'Dates of attendance', 'List employment, academic or other achievements|List employment, academic or other achievements|List employment, academic or other achievements|;', 'List computer, language or other personal skills here,List computer, language or other personal skills here,;', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/10831/license-agreement-document.docx'),
(1, 3, 'Simhadri\n			\n		', '\n			\n				\n				\n					', '\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n		', '\n			\n				\n				\n					', ' 19333\n			\n		', ' PA', '\n			\n				\n				\n					', '\n			\n				\n				\n					', '', '', '', ';', ';', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/17884/license-agreement-document.docx'),
(1, 4, 'Simhadri', 'Rahul', '\n			\n				\n				\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n					\n				\n		', '\n			\n				\n				\n					', ' 19333\n			\n		', ' PA', '\n			\n				\n				\n					', '\n			\n				\n				\n					', '', '', '', ';', ';', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/31573/license-agreement-document.docx'),
(1, 5, 'Simhadri', 'Rahul', '', '\n			\n				\n				\n					', ' 19333\n			\n		', ' PA', '\n			\n				\n				\n					', '\n			\n				\n				\n					', '', '', '', ';', ';', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/6506/license-agreement-document.docx'),
(1, 6, 'Simhadri', 'Rahul', '', '\n			\n				\n				\n					', ' 19333\n			\n		', ' PA', '\n			\n				\n				\n					', '\n			\n				\n				\n					', '', '', '', ';', ';', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/10089/license-agreement-document.docx'),
(1, 7, 'Simhadri', 'Rahul', '', '\n			\n				\n				\n					', ' 19333\n			\n		', ' PA', '\n			\n				\n				\n					', '\n			\n				\n				\n					', '', '', '', ';', ';', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/30190/license-agreement-document.docx'),
(1, 8, 'Simhadri', 'Rahul', '', '\n			\n				\n				\n					', ' 19333\n			\n		', ' PA', '\n			\n				\n				\n					', '\n			\n				\n				\n					', '', '', '', ';', ';', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/27279/license-agreement-document.docx'),
(1, 9, 'Simhadri', 'Rahul', '', '\n			\n				\n				\n					', ' 19333\n			\n		', ' PA', '\n			\n				\n				\n					', '\n			\n				\n				\n					', '', '', '', ';', ';', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/8476/license-agreement-document.docx'),
(1, 10, 'Simhadri', 'Rahul', '', '\n			\n				\n				\n					', ' 19333\n			\n		', ' PA', '\n			\n				\n				\n					', '\n			\n				\n				\n					', '', '', '', ';', ';', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/20773/license-agreement-document.docx'),
(1, 11, 'Â«Last_nameÂ»', 'Â«First_nameÂ»', 'Â«street_addressÂ»', ' Â«CityÂ»', ' Â«zipÂ»', ' Â«StateÂ»', 'Â«phone_noÂ»', 'Â«emailÂ»', 'Â«degreeÂ»â€“ Â«scho', 'Â«school_datesÂ»', 'Skills', ';', 'Â«skillsÂ»,;', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/762/template.docx'),
(1, 12, 'Simhadri', 'Rahul', 'Street Address', ' City', ' Zip Code ', ' State', 'Phone Number', 'Email address', 'MS ', 'Villanova ', 'Dec 2011', 'List employment, academic or other achievements|List employment, academic or other achievements|List employment, academic or other achievements|;', 'C,C++,java,cobal,mysql.,List computer, language or other personal skills here,;', '12', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/8363/Rahul Simhadri.docx'),
(1, 13, 'Simhadri', 'Rahul', '', '\n			\n				\n				\n					', ' 19333\n			\n		', ' PA', '\n			\n				\n				\n					', '\n			\n				\n				\n					', '', '', '', ';', ';', '0', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/4368/license-agreement-document.docx'),
(1, 14, 'S', 'Rahul', '', 'Smls', 'slmsl', 'AZ', 'slmsl', 'sravan.anumula@gmail', 'â€“ villanoab', 'mdskl', '', ';', 'al,djd,jhdndkj,nndkjdj,;', '3', 'files/1/qg6vckb0ubq3e1ksh4eeo76pe1/13064/license-agreement-document.doc');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `uid` int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(60) NOT NULL,
  `pass` varchar(128) NOT NULL,
  `mail` varchar(200) NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `mail` (`mail`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=6 ;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`uid`, `name`, `pass`, `mail`) VALUES
(1, 'admin', '63a9f0ea7bb98050796b649e85481845', 'rahul_simhadri@yahoo.co.in'),
(3, 'test', '098f6bcd4621d373cade4e832627b4f6', 'test@gmail.com'),
(4, 'anu', '89a4b5bd7d02ad1e342c960e6a98365c', 'anu'),
(5, 'finaltest', '8ca62ab13163367c47a5bed31957ff7f', 'maddoghot_rahul@yahoo.co.in');

--
-- Constraints for dumped tables
--

--
-- Constraints for table `resume`
--
ALTER TABLE `resume`
  ADD CONSTRAINT `resume_ibfk_1` FOREIGN KEY (`uid`) REFERENCES `users` (`uid`) ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
